<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.flyfish</groupId>
        <artifactId>flyfish-validation-parent</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>flyfish-validation-jakarta</artifactId>
    <packaging>jar</packaging>
    <name>Flyfish Validation Jakarta</name>
    <description>Bean Validation 3 / jakarta.validation 约束适配</description>
    <dependencies>
        <dependency>
            <groupId>dev.flyfish</groupId>
            <artifactId>flyfish-validation-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>${jakarta.validation.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>${hibernate.validator8.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.expressly</groupId>
            <artifactId>expressly</artifactId>
            <version>5.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <properties>
        <maven.compiler.release>8</maven.compiler.release>
        <automatic.module.name>dev.flyfish.validation.jakarta</automatic.module.name>
    </properties>
</project>
